# Generated by Django 4.2.7 on 2023-12-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Amazone", "0004_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="mobile",
            field=models.BigIntegerField(default=1),
        ),
    ]
